// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ4NKbZ1qBYCblTvSeZ5_Mjgt2Q-fZY3g',
    appId: '1:940637611175:web:4e6852a6ce60b201d26782',
    messagingSenderId: '940637611175',
    projectId: 'adptv-learning-test',
    authDomain: 'adptv-learning-test.firebaseapp.com',
    storageBucket: 'adptv-learning-test.firebasestorage.app',
    measurementId: 'G-YEPCHK20CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCt1_FAhiLEdvoXtl__MBI0O9wUttklZE',
    appId: '1:940637611175:android:bb155dbac4ca19d2d26782',
    messagingSenderId: '940637611175',
    projectId: 'adptv-learning-test',
    storageBucket: 'adptv-learning-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFugjTGNxo-vPGfy6If68bLRG5a2IPpY',
    appId: '1:940637611175:ios:648c54903e3b05a5d26782',
    messagingSenderId: '940637611175',
    projectId: 'adptv-learning-test',
    storageBucket: 'adptv-learning-test.firebasestorage.app',
    iosBundleId: 'com.park.ease.app',
  );
}
